/*! Generated by redux-scfld not for editing */

// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_CONFIG = 'config';
export const NAMESPACE_USER = 'user';

export const NAMESPACES = [
  NAMESPACE_CONFIG,
  NAMESPACE_USER,
];
// Generated Types
export const CONFIG_SET = 'CONFIG_SET';
export const USER_LOAD = 'USER_LOAD';
export const USER_SET = 'USER_SET';
