/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_USER,
  USER_LOAD,
} from '../../types';

export default action(NAMESPACE_USER, USER_LOAD, (getState, sessionId) => {
  if (!sessionId) {
    sessionId = localStorage.getItem('sessionId');
  }
  return {};
});
