/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_USER,
  USER_SET,
} from '../../types';

export default action(NAMESPACE_USER, USER_SET, (getState, user) => {
  return user;
});
