/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_CONFIG,
  CONFIG_SET,
} from '../../types';

export default action(NAMESPACE_CONFIG, CONFIG_SET, (getState, config) => {
  return config;
});
